### ISSUE TITLE
java.lang.NoSuchMethodError: org.lwjglx.debug.RT.returnValue(DLorg/lwjglx/debug/MethodCall;)D

### ISSUE THREAD

**Issue by Niko-sk2x** [LWJGLX/debug#16]
I attempted to run Minecraft 1.13 snapshot with lwjglx debug (because on my system it has a strange memory leak and I'm trying to find the cause on my own). After adding nothrow and trace options, I got this exception:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.lwjglx.debug.RT.returnValue(DLorg/lwjglx/debug/MethodCall;)D
	at org.lwjglx.debug.$Proxy$44.10(Unknown Source)
	at bjh.B(SourceFile:2117)
	at net.minecraft.client.main.Main.main(SourceFile:45)
```

**Comment by httpdigest** [comment]
Thanks a lot for the bug report! That method was indeed missing and get only reported at runtime since they are being called by dynamically generated code. Fixed with: https://github.com/LWJGLX/debug/commit/daf61f73da0452fb13d8e8e01dcbc3b122f3c1a8

**Comment by Niko-sk2x** [comment]
It works now. The issue can be closed. Looks like lwjglx debug didn't help me anyway, I don't see any potential source of memory leak there.

**Comment by httpdigest** [comment]
LWJGL 3 also provides a binding to Remotery, which is a much more sophisticated profiler. Maybe you can integrate that and see where the problem is (if any).

**Comment by Niko-sk2x** [comment]
I assume that would mean modifying the code. As I'm not one of Minecraft developers and just write mods, for that I would need to get the deobfuscation mappings (which involves either getting a non-public tool, or remaking that tool myself, or work with obfuscated code). So at that point I will probably try to figure it out in a different way, or just give up and hope the developers will figure it out and fix it (with 2 or 3 users affected so far, it may not happen). I just wanted to see if there is anythign i can do without touching the code.
