### ISSUE TITLE
Issues when running on working code

### ISSUE THREAD

**Issue by Guerra24** [LWJGLX/debug#20]
When running with the profiler I got it to throw exceptions that does not happen under normal circumstances.

[Log without agent.txt](https://github.com/LWJGLX/debug/files/2898600/Log.without.agent.txt)
[Log with agent.txt](https://github.com/LWJGLX/debug/files/2898601/Log.with.agent.txt)

I've attached logs with and without the agent. It seems to mess with the state in unintended ways because these errors are from my own calls to `glGetError`. Also, I'm using multi-threaded shared-context to smooth texture loading but only some errors appear to be caused by that.

**Comment by httpdigest** [comment]
Yeah, share groups haven't been given thorough thoughts in the design. I've changed it to make LWJGLX/debug aware of shared texture and buffer objects now. Do you have a MCVE that I could try?

**Comment by Guerra24** [comment]
I do not have a MCVE on hand.

I tried it with the new build and it successfully loads but still throws a lot of OGL Errors. I've found that most if not all of them are caused by the `texImage2D` call, it happens with textures generated and used in the same thread-context and shared ones.

**Comment by httpdigest** [comment]
Are there any GL error outputs when you do not use the agent and instead install an OpenGL debug callback? Can be done with LWJGL3 via `Callback debugProc = GLUtil.setupDebugMessageCallback();`.
LWJGLX/debug itself does not issue any OpenGL calls itself, but for the most part merely installs a synchronous GL message callback, and if that is not possible/supported calls glGetError() after each OpenGL call done by the user application. Additionally, a few validations are being done but that will not interfere with the OpenGL state itself, since for that no OpenGL calls are issued.

**Comment by Guerra24** [comment]
With the debug callback there are no errors and I can confirm that is the `glTexImage2D` call that causes my own checks to trigger.

**Comment by httpdigest** [comment]
What do you mean by _your own checks_? Please provide more information. Stacktrace, Tracelog (start the agent with `-javaagent:lwjglx-debug-1.0.0.jar=t;o=trace.log` of the OpenGL calls, MCVE. Without any more information, I'm afraid, I cannot help any further.

**Comment by httpdigest** [comment]
Do your glGetError() calls yield any error when you do not use profiling but merely use the validation feature of the agent via `-javaagent:lwjglx-debug-1.0.0.jar` without any agent arguments?

**Comment by Guerra24** [comment]
Oh sorry, with my own checks I mean the `glGetError` calls.

[I've made a MCVE that replicates the issue.](https://gist.github.com/Guerra24/06e2295178b1e697ae67700e2033c235)

No, only when using the profiler I get these errors and the validation feature works fine.

**Comment by httpdigest** [comment]
Many thanks for that! I've tested it and indeed I am getting the GL error, too. Will get onto a fix right away. Thanks for your supportive work!

**Comment by httpdigest** [comment]
Next build is up. It was a seemingly innocent call to `glGetTexParameteri(target, GL_GENERATE_MIPMAP)` which was used to query whether automatic mipmap generation was enabled for the texture bound to `target` which might have been set via `glTexParameteri()`. But querying that parameter apparently is not allowed (at least in a core context). Has been replaced with tracking glTexParameteri() calls. Please try again.

**Comment by Guerra24** [comment]
Its working correctly, thanks you for your time fixing these issues. 👍
