### ISSUE TITLE
org.lwjglx.debug.opengl.GL.createCapabilities(GL.java:59) fires java.lang.NullPointerException

### ISSUE THREAD

**Issue by elect86** [LWJGLX/debug#21]
Hi,

as titled, it crashes [here](https://github.com/LWJGLX/debug/blob/master/src/org/lwjglx/debug/opengl/GL.java#L58):

        Context context = CURRENT_CONTEXT.get();
        context.caps = caps;

I double cheched and `context` is indeed null

In my app I do the following:

        glfwWindow = GlfwWindow.fromWin32Window(hwnd).apply {
            makeContextCurrent()
            println("current: $isCurrent")
            createCapabilities(forwardCompatible = false)
        }

- create the glfw window
- make context current
- check if it's really current (`glfwGetCurrentContext == window.handle`)
- and then create the capabilities with the desidered forwardCompatibility option

And the last step is exactly where debug crashes

What is wrong?

ps: `glfw` is already initialized at that point, I also have `GLFWErrorCallback.createPrint().set()` but I dont get any error from there

**Comment by elect86** [comment]
I cant reproduce anymore, don't know what was the problem..

**Comment by httpdigest** [comment]
Hmm.. you would get this exception if you had called glfwMakeContextCurrent with 0L while no context was current at the moment. This bug should not happen, of course, and I will fix this. Thanks for mentioning!

**Comment by httpdigest** [comment]
Actually, what I wrote above was wrong. I've tried a few things but cannot reproduce this error also. Do you happen to use multiple threads and migrate the GL context between different threads?

**Comment by elect86** [comment]
no. 

I'm sorry I cannot specify what caused that, probably too much spaghetti debugging..

**Comment by httpdigest** [comment]
Alrighty then. :) When it happens again, I'd be glad if you could post here again.

**Comment by elect86** [comment]
Sure, thanks for the cool lib, I fixed `glfwInit()` to be called from the main thread though
